apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      sample-app: web
  template:
    metadata:
      labels:
        sample-app: web
    spec:
      containers:
      - name: sample-app
        image: subhayandsgpt/sample_app
---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001